export * from './audit.service';
import { AuditService } from './audit.service';
export * from './break-templates.service';
import { BreakTemplatesService } from './break-templates.service';
export * from './custom-entities.service';
import { CustomEntitiesService } from './custom-entities.service';
export * from './device-catalogs.service';
import { DeviceCatalogsService } from './device-catalogs.service';
export * from './devices.service';
import { DevicesService } from './devices.service';
export * from './entitlements.service';
import { EntitlementsService } from './entitlements.service';
export * from './resource-configurations.service';
import { ResourceConfigurationsService } from './resource-configurations.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './screens.service';
import { ScreensService } from './screens.service';
export * from './settings.service';
import { SettingsService } from './settings.service';
export * from './shift-templates.service';
import { ShiftTemplatesService } from './shift-templates.service';
export * from './site-branding.service';
import { SiteBrandingService } from './site-branding.service';
export * from './team-routing.service';
import { TeamRoutingService } from './team-routing.service';
export * from './teams.service';
import { TeamsService } from './teams.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './workspace.service';
import { WorkspaceService } from './workspace.service';
export const APIS = [AuditService, BreakTemplatesService, CustomEntitiesService, DeviceCatalogsService, DevicesService, EntitlementsService, ResourceConfigurationsService, RolesService, ScreensService, SettingsService, ShiftTemplatesService, SiteBrandingService, TeamRoutingService, TeamsService, UsersService, WorkspaceService];
