/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { ApiResponse } from '../model/api-response';
// @ts-ignore
import { ResourceConfigurationEntry } from '../model/resource-configuration-entry';
// @ts-ignore
import { ResourceConfigurationEnvelope } from '../model/resource-configuration-envelope';
// @ts-ignore
import { ResourceScopeType } from '../model/resource-scope-type';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { CoreConfiguration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class ResourceConfigurationsService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: CoreConfiguration) {
        super(basePath, configuration);
    }

    /**
     * The custom variables of one scoped resource
     * @endpoint get /api/v1/resource-configurations/{scopeType}/{resourceExternalId}
     * @param scopeType 
     * @param resourceExternalId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public readResourceConfiguration(scopeType: ResourceScopeType, resourceExternalId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ResourceConfigurationEnvelope>;
    public readResourceConfiguration(scopeType: ResourceScopeType, resourceExternalId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ResourceConfigurationEnvelope>>;
    public readResourceConfiguration(scopeType: ResourceScopeType, resourceExternalId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ResourceConfigurationEnvelope>>;
    public readResourceConfiguration(scopeType: ResourceScopeType, resourceExternalId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (scopeType === null || scopeType === undefined) {
            throw new Error('Required parameter scopeType was null or undefined when calling readResourceConfiguration.');
        }
        if (resourceExternalId === null || resourceExternalId === undefined) {
            throw new Error('Required parameter resourceExternalId was null or undefined when calling readResourceConfiguration.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/resource-configurations/${this.configuration.encodeParam({name: "scopeType", value: scopeType, in: "path", style: "simple", explode: false, dataType: "ResourceScopeType", dataFormat: undefined})}/${this.configuration.encodeParam({name: "resourceExternalId", value: resourceExternalId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ResourceConfigurationEnvelope>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Replace the custom variables of one scoped resource
     * Declarative — the request\&#39;s set is the whole set for that resource.
     * @endpoint put /api/v1/resource-configurations/{scopeType}/{resourceExternalId}
     * @param scopeType 
     * @param resourceExternalId 
     * @param resourceConfigurationEntry 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public replaceResourceConfiguration(scopeType: ResourceScopeType, resourceExternalId: string, resourceConfigurationEntry: Array<ResourceConfigurationEntry>, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ResourceConfigurationEnvelope>;
    public replaceResourceConfiguration(scopeType: ResourceScopeType, resourceExternalId: string, resourceConfigurationEntry: Array<ResourceConfigurationEntry>, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ResourceConfigurationEnvelope>>;
    public replaceResourceConfiguration(scopeType: ResourceScopeType, resourceExternalId: string, resourceConfigurationEntry: Array<ResourceConfigurationEntry>, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ResourceConfigurationEnvelope>>;
    public replaceResourceConfiguration(scopeType: ResourceScopeType, resourceExternalId: string, resourceConfigurationEntry: Array<ResourceConfigurationEntry>, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (scopeType === null || scopeType === undefined) {
            throw new Error('Required parameter scopeType was null or undefined when calling replaceResourceConfiguration.');
        }
        if (resourceExternalId === null || resourceExternalId === undefined) {
            throw new Error('Required parameter resourceExternalId was null or undefined when calling replaceResourceConfiguration.');
        }
        if (resourceConfigurationEntry === null || resourceConfigurationEntry === undefined) {
            throw new Error('Required parameter resourceConfigurationEntry was null or undefined when calling replaceResourceConfiguration.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/resource-configurations/${this.configuration.encodeParam({name: "scopeType", value: scopeType, in: "path", style: "simple", explode: false, dataType: "ResourceScopeType", dataFormat: undefined})}/${this.configuration.encodeParam({name: "resourceExternalId", value: resourceExternalId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ResourceConfigurationEnvelope>('put', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: resourceConfigurationEntry,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
