/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuditEventSummary { 
    occurredAt: string;
    actor: string;
    entityType: string;
    entityExternalId?: string;
    action: AuditEventSummary.ActionEnum;
    detail?: string;
}
export namespace AuditEventSummary {
    export const ActionEnum = {
        Created: 'CREATED',
        Updated: 'UPDATED',
        Retired: 'RETIRED',
        Reinstated: 'REINSTATED',
        Replaced: 'REPLACED'
    } as const;
    export type ActionEnum = typeof ActionEnum[keyof typeof ActionEnum];
}


