/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BreakTimingItem { 
    /**
     * A wall-clock time of day, HH:mm or HH:mm:ss.
     */
    startTime: string;
    durationMinutes: number;
}

