/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ColumnPreference { 
    columnCode: string;
    displayOrder: number;
    widthPx?: number;
    visible?: boolean;
}

