/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateScreenRequest { 
    name: string;
    processDefinitionKey: string;
    nodeReference: string;
    belowExpectedSec?: number;
    expectedSec?: number;
    maxSec?: number;
}

