/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HandlingMethod } from './handling-method';


export interface CreateTeamRequest { 
    siteExternalId: string;
    name: string;
    description?: string;
    handlingMethod: HandlingMethod;
    shiftTemplateExternalId?: string;
    breakTemplateExternalId?: string;
    memberUserExternalIds?: Array<string>;
}
export namespace CreateTeamRequest {
}


