/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateFilterRequest { 
    gridCode: string;
    name: string;
    filterJson: string;
    isDefault?: boolean;
}

