/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BreakTimingItem } from './break-timing-item';


export interface CreateBreakTemplateRequest { 
    name: string;
    description?: string;
    timings?: Array<BreakTimingItem>;
}

