/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateShiftTemplateRequest { 
    name: string;
    timeZone: string;
    /**
     * A wall-clock time of day, HH:mm or HH:mm:ss.
     */
    startTime: string;
    /**
     * A wall-clock time of day, HH:mm or HH:mm:ss.
     */
    endTime: string;
}

