/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomEntityFieldType } from './custom-entity-field-type';


export interface CustomEntityFieldSummary { 
    externalId: string;
    /**
     * Stable allow-listed storage identifier; never derived from the display name. The fixed row/scope names are reserved.
     */
    identifier: string;
    /**
     * Administrator-facing label, unique within this entity.
     */
    displayName: string;
    type: CustomEntityFieldType;
    /**
     * Required for TEXT and absent for every other type.
     */
    maxLength?: number;
    /**
     * Required for NUMBER and absent for every other type.
     */
    precision?: number;
    /**
     * Required for NUMBER, no greater than precision, and absent otherwise.
     */
    scale?: number;
    nullable: boolean;
    /**
     * Exactly one field in a new declaration; it is immutable on this declaration-only surface.
     */
    businessKey: boolean;
    ordinal: number;
}
export namespace CustomEntityFieldSummary {
}


