/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The declared value vocabulary. Its eventual SQL representation and the permitted changes between types belong to the controlled-executor decision. 
 */
export const CustomEntityFieldType = {
    Text: 'TEXT',
    Number: 'NUMBER',
    Boolean: 'BOOLEAN',
    Date: 'DATE'
} as const;
export type CustomEntityFieldType = typeof CustomEntityFieldType[keyof typeof CustomEntityFieldType];

