/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * REFERENCE is a maintained lookup list; EVENT is append-oriented event data.
 */
export const CustomEntityKind = {
    Reference: 'REFERENCE',
    Event: 'EVENT'
} as const;
export type CustomEntityKind = typeof CustomEntityKind[keyof typeof CustomEntityKind];

