/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomEntityKind } from './custom-entity-kind';
import { CustomEntityFieldSummary } from './custom-entity-field-summary';


export interface CustomEntitySummary { 
    externalId: string;
    siteExternalId: string;
    name: string;
    kind: CustomEntityKind;
    /**
     * Stable ce_-prefixed identifier reserved for the controlled executor; its presence does not mean a table exists.
     */
    tableIdentifier: string;
    /**
     * Fixed future internal integer-key column (`row_id`), independent of the table name.
     */
    rowIdColumn: string;
    /**
     * Fixed future external-id column (`external_id`), independent of the table name.
     */
    rowExternalIdColumn: string;
    /**
     * Fixed future scope column (`site_external_id`) required by the site scope seam.
     */
    rowSiteExternalIdColumn: string;
    declarationVersion: number;
    fields: Array<CustomEntityFieldSummary>;
    createdAt: string;
    updatedAt: string;
}
export namespace CustomEntitySummary {
}


