/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomEntityKind } from './custom-entity-kind';
import { DeclareCustomEntityFieldRequest } from './declare-custom-entity-field-request';


export interface DeclareCustomEntityRequest { 
    name: string;
    kind: CustomEntityKind;
    fields: Array<DeclareCustomEntityFieldRequest>;
}
export namespace DeclareCustomEntityRequest {
}


