/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomEntityFieldType } from './custom-entity-field-type';


export interface DeclareCustomEntityFieldRequest { 
    /**
     * `row_id`, `external_id` and `site_external_id` are reserved.
     */
    identifier: string;
    /**
     * Must be unique within the entity.
     */
    displayName: string;
    type: CustomEntityFieldType;
    maxLength?: number;
    precision?: number;
    scale?: number;
    nullable: boolean;
    businessKey: boolean;
    ordinal: number;
}
export namespace DeclareCustomEntityFieldRequest {
}


