/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeviceTypeSummary { 
    externalId: string;
    code: string;
    /**
     * Display-only.
     */
    name: string;
    /**
     * The per-type JSON form-schema driving the admin UI. Deliberately a JSON document (translation rule 11).
     */
    formSchema?: string;
}

