/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 1.x compared this with LOWER(?) and leaned on collation; here it is one casing.
 */
export const DeviceMode = {
    Io: 'IO',
    DataCapture: 'DATA_CAPTURE'
} as const;
export type DeviceMode = typeof DeviceMode[keyof typeof DeviceMode];

