/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IoAssignmentItem } from './io-assignment-item';
import { PerspectiveItem } from './perspective-item';
import { DeviceMode } from './device-mode';


export interface DeviceSummary { 
    externalId: string;
    laneExternalId: string;
    siteExternalId: string;
    deviceTypeCode: string;
    name: string;
    address?: string;
    mode?: DeviceMode;
    alias?: string;
    model?: string;
    firmwareVersion?: string;
    description?: string;
    resolution?: string;
    ipAddress?: string;
    streamType?: string;
    port?: number;
    protocol: string;
    manufacturer?: string;
    deviceUrl?: string;
    devicePortalUrl?: string;
    /**
     * .NET plugin-load parameter — load-bearing for the frozen config poll (§D2).
     */
    assemblyName?: string;
    className?: string;
    dataCaptureMode?: string;
    waitTime?: number;
    ioAssignments: Array<IoAssignmentItem>;
    perspectives: Array<PerspectiveItem>;
    retired: boolean;
    createdAt?: string;
}
export namespace DeviceSummary {
}


