/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EntitlementActionItem { 
    externalId: string;
    /**
     * The stable machine code — the contract. Grant by this, gate by this.
     */
    code: string;
    /**
     * Display-only.
     */
    name: string;
    /**
     * The 1.x licence-gate string, verbatim. NOT unique across the tree — licence filtering by route is coarser than the catalog. 
     */
    licenceRoute: string;
}

