/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntitlementApplication } from './entitlement-application';


export interface EntitlementTree { 
    applications: Array<EntitlementApplication>;
}

