/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntitlementModule } from './entitlement-module';


export interface EntitlementApplication { 
    externalId: string;
    code: string;
    name: string;
    modules: Array<EntitlementModule>;
}

