/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntitlementActionItem } from './entitlement-action-item';


export interface EntitlementSubModule { 
    externalId: string;
    code: string;
    name: string;
    actionItems: Array<EntitlementActionItem>;
}

