/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddCustomEntityFieldRequest } from './add-custom-entity-field-request';


/**
 * At least one of name or addFields must carry a real change.
 */
export interface EvolveCustomEntityDeclarationRequest { 
    name?: string;
    addFields?: Array<AddCustomEntityFieldRequest>;
}

