/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ColumnPreference } from './column-preference';


export interface GridPreferences { 
    gridCode: string;
    columns: Array<ColumnPreference>;
}

