/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * How work reaches this team\'s members (§C1). One casing — the database checks it.
 */
export const HandlingMethod = {
    Push: 'PUSH',
    Prompt: 'PROMPT'
} as const;
export type HandlingMethod = typeof HandlingMethod[keyof typeof HandlingMethod];

