/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PortType } from './port-type';


export interface IoAssignmentItem { 
    portType: PortType;
    ioPort: number;
    /**
     * A code from the IO port name catalog (DI1 … DO3 … R2 … FRONT_MIC).
     */
    portNameCode?: string;
    portAliasName?: string;
    reverseState?: boolean;
    initialHigh?: boolean;
    dataCapture?: boolean;
    gosAudio?: boolean;
    /**
     * Edge-suppression semantics — edge reads these; silence is configured, never accidental.
     */
    produceTrueMessage?: boolean;
    produceFalseMessage?: boolean;
    waitTime?: number;
}
export namespace IoAssignmentItem {
}


