/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PortType } from './port-type';


export interface IoPortNameSummary { 
    externalId: string;
    portType: PortType;
    code: string;
    name: string;
}
export namespace IoPortNameSummary {
}


