/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PerspectiveItem { 
    name: string;
    pan?: number;
    tilt?: number;
    zoom?: number;
}

