/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The unified port-type enum — TitleCase in one 1.x table, lowercase in another; one casing here.
 */
export const PortType = {
    Input: 'INPUT',
    Output: 'OUTPUT',
    Relay: 'RELAY',
    Audio: 'AUDIO',
    Tone: 'TONE'
} as const;
export type PortType = typeof PortType[keyof typeof PortType];

