/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoutingRule } from './routing-rule';


export interface ReplaceRoutingRulesRequest { 
    rules: Array<RoutingRule>;
}

