/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceConfigurationEntry } from './resource-configuration-entry';
import { ResourceScopeType } from './resource-scope-type';


export interface ResourceConfigurationView { 
    scopeType: ResourceScopeType;
    resourceExternalId: string;
    entries: Array<ResourceConfigurationEntry>;
}
export namespace ResourceConfigurationView {
}


