/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMeta } from './page-meta';
import { ApiStatus } from './api-status';
import { ApiError } from './api-error';
import { ResourceConfigurationView } from './resource-configuration-view';


export interface ResourceConfigurationEnvelope { 
    status: ApiStatus;
    /**
     * The machine-readable code. `OK` on success. A caller branches on this and never on `message`, so improving the wording of a message can never break an integration. 
     */
    code: string;
    /**
     * Human-readable, and never internal detail. No stack trace, no exception text, no schema or table name reaches a caller on any path. 
     */
    message?: string;
    data?: ResourceConfigurationView;
    /**
     * Present when more than the top-level code is worth saying.
     */
    errors?: Array<ApiError>;
    page?: PageMeta;
    /**
     * Echoed back so a caller can quote it in a support request and an operator can find the exact request in the log. Supplied by the caller as `X-Request-Id`, or generated. 
     */
    requestId?: string;
}
export namespace ResourceConfigurationEnvelope {
}


