/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoleSummary { 
    externalId: string;
    name: string;
    description?: string;
    /**
     * The sites this role is scoped to (role-based site scoping — 1.x user↔site mapping is dead).
     */
    siteExternalIds: Array<string>;
    /**
     * The granted catalog leaves, by stable code.
     */
    entitlementCodes: Array<string>;
    retired: boolean;
    createdAt?: string;
}

