/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoutingRule { 
    screenExternalId: string;
    laneExternalId: string;
    /**
     * Lower = more urgent. Absent = unprioritised, ordered after the prioritised.
     */
    priority?: number;
}

