/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SavedFilterSummary { 
    externalId: string;
    gridCode: string;
    name: string;
    filterJson: string;
    filterSchemaVersion: number;
    isDefault: boolean;
    createdAt?: string;
}

