/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScreenSummary { 
    externalId?: string;
    name?: string;
    processDefinitionKey?: string;
    /**
     * The wait-state node this screen fronts, in the engine\'s vocabulary.
     */
    nodeReference?: string;
    /**
     * Per-screen threshold; absent = no below-expected threshold (there is no global fallback for this one).
     */
    belowExpectedSec?: number;
    /**
     * Per-screen threshold; absent = the EXPECTED_PROCESSING_TIME_SEC setting decides.
     */
    expectedSec?: number;
    /**
     * Per-screen threshold; absent = the MAX_PROCESSING_TIME_SEC setting decides. This is the one the SLA timer arms from.
     */
    maxSec?: number;
    retired?: boolean;
}

