/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SettingSummary { 
    key: string;
    valueType: SettingSummary.ValueTypeEnum;
    description?: string;
    defaultValue?: string;
    /**
     * The current value, absent when never written (the default applies).
     */
    value?: string;
    updatedBy?: string;
    updatedAt?: string;
}
export namespace SettingSummary {
    export const ValueTypeEnum = {
        String: 'STRING',
        Integer: 'INTEGER',
        Boolean: 'BOOLEAN'
    } as const;
    export type ValueTypeEnum = typeof ValueTypeEnum[keyof typeof ValueTypeEnum];
}


