/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShiftTemplateSummary { 
    externalId: string;
    name: string;
    /**
     * IANA zone id, validated against the JVM\'s tz database.
     */
    timeZone: string;
    /**
     * A wall-clock time of day, HH:mm or HH:mm:ss.
     */
    startTime: string;
    /**
     * A wall-clock time of day, HH:mm or HH:mm:ss.
     */
    endTime: string;
    /**
     * Computed — end at or before start crosses midnight; equal times are the 24-hour shift.
     */
    overnight: boolean;
    /**
     * Computed, never stored — 1.x stored a duration in a TIME column and that defect does not port.
     */
    durationMinutes: number;
    retired: boolean;
    createdAt?: string;
}

