/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SiteLanguageItem } from './site-language-item';
import { SiteColorItem } from './site-color-item';


export interface SiteBranding { 
    siteExternalId: string;
    colors: Array<SiteColorItem>;
    languages: Array<SiteLanguageItem>;
}

