/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SiteColorItem { 
    code: string;
    /**
     * #RRGGBB or #RRGGBBAA; normalized to #RRGGBBAA on write.
     */
    hexValue: string;
}

