/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateScreenRequest { 
    name?: string;
    processDefinitionKey?: string;
    nodeReference?: string;
    /**
     * 0 clears the threshold back to the fallback.
     */
    belowExpectedSec?: number;
    /**
     * 0 clears the threshold back to the fallback.
     */
    expectedSec?: number;
    /**
     * 0 clears the threshold back to the fallback.
     */
    maxSec?: number;
    retired?: boolean;
}

