/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HandlingMethod } from './handling-method';


/**
 * Absent fields are unchanged; `memberUserExternalIds` replaces the membership when present; an empty string clears a template reference. 
 */
export interface UpdateTeamRequest { 
    name?: string;
    description?: string;
    handlingMethod?: HandlingMethod;
    shiftTemplateExternalId?: string;
    breakTemplateExternalId?: string;
    memberUserExternalIds?: Array<string>;
    retired?: boolean;
}
export namespace UpdateTeamRequest {
}


