/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Absent fields are unchanged.
 */
export interface UpdateUserRequest { 
    displayName?: string;
    firstName?: string;
    middleName?: string;
    lastName?: string;
    email?: string;
    profileImageUrl?: string;
    languageCode?: string;
    keycloakSubject?: string;
    roleExternalId?: string;
    privacyAcceptedAt?: string;
    termsAcceptedAt?: string;
    retired?: boolean;
}

