/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeviceMode } from './device-mode';


/**
 * Absent fields are unchanged.
 */
export interface UpdateDeviceRequest { 
    name?: string;
    deviceTypeCode?: string;
    address?: string;
    mode?: DeviceMode;
    alias?: string;
    model?: string;
    firmwareVersion?: string;
    description?: string;
    resolution?: string;
    ipAddress?: string;
    streamType?: string;
    port?: number;
    protocol?: string;
    manufacturer?: string;
    deviceUrl?: string;
    devicePortalUrl?: string;
    assemblyName?: string;
    className?: string;
    dataCaptureMode?: string;
    waitTime?: number;
}
export namespace UpdateDeviceRequest {
}


