/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BreakTimingItem } from './break-timing-item';


/**
 * Absent fields are unchanged; `timings` replaces the set when present.
 */
export interface UpdateBreakTemplateRequest { 
    name?: string;
    description?: string;
    timings?: Array<BreakTimingItem>;
    retired?: boolean;
}

