/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Absent fields are unchanged; `entitlementCodes` and `siteExternalIds` REPLACE their sets when present. 
 */
export interface UpdateRoleRequest { 
    name?: string;
    description?: string;
    siteExternalIds?: Array<string>;
    entitlementCodes?: Array<string>;
    retired?: boolean;
}

