/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A platform user — profile and claim mapping. No credential ever appears here.
 */
export interface UserSummary { 
    /**
     * Minted by the service on creation, never reused (§B8).
     */
    externalId: string;
    displayName: string;
    firstName?: string;
    middleName?: string;
    lastName?: string;
    email: string;
    profileImageUrl?: string;
    languageCode?: string;
    /**
     * The identity-provider subject this user\'s tokens carry, once linked.
     */
    keycloakSubject?: string;
    privacyAcceptedAt?: string;
    termsAcceptedAt?: string;
    /**
     * Exactly one role per user.
     */
    roleExternalId: string;
    retired: boolean;
    createdAt?: string;
}

