/**
 * orca-core
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ColumnPreference } from './column-preference';


export interface WorkspaceGrid { 
    gridCode: string;
    title: string;
    /**
     * The grid\'s default layout, as a JSON document (rule 11 — a UI schema).
     */
    defaultColumns?: string;
    /**
     * The caller\'s own column preferences; empty when the defaults apply.
     */
    columns: Array<ColumnPreference>;
}

