/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One error inside the envelope\'s `errors` array. A validation failure over four fields is four entries, not four round trips. 
 */
export interface ApiError { 
    /**
     * The machine-readable code for THIS error, which may be more specific than the envelope\'s.
     */
    code: string;
    /**
     * The input this error is about, absent when it is about the request as a whole.
     */
    field?: string;
    /**
     * Written for a developer reading a log. Never derived from an exception\'s text.
     */
    message?: string;
}

