/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Whether this response carries a result or a failure. Two values, deliberately: a caller branches on `code` to tell one failure from another, and on this only to know which half of the body to read. 
 */
export const ApiStatus = {
    Success: 'SUCCESS',
    Error: 'ERROR'
} as const;
export type ApiStatus = typeof ApiStatus[keyof typeof ApiStatus];

