/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CompletedWorkGridRequest { 
    status?: CompletedWorkGridRequest.StatusEnum;
    laneExternalId?: string;
    assignee?: string;
    completedFrom?: string;
    completedUntil?: string;
    limit?: number;
}
export namespace CompletedWorkGridRequest {
    export const StatusEnum = {
        Completed: 'COMPLETED',
        Failed: 'FAILED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


