/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CompleteWorkItemRequest { 
    /**
     * The operator\'s corrected data, stored verbatim on the item.
     */
    correctedEventData?: string;
}

