/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeviceEvent } from './device-event';


export interface DeviceEventBatch { 
    events: Array<DeviceEvent>;
}

