/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeviceEvent { 
    /**
     * The producer\'s dedup key — the camera\'s own `EventGuid` for a plate read. The idempotency key, and the reason a redelivery has one effect. 
     */
    eventUuid: string;
    /**
     * The lane, in core\'s published vocabulary (`core.topology_lane`).
     */
    laneExternalId: string;
    deviceExternalId?: string;
    /**
     * `lpr.capture`, … ⚠️ PROVISIONAL: nothing in the architecture enumerates these.
     */
    eventType: string;
    /**
     * When the device observed it. The device\'s clock, not this service\'s.
     */
    occurredAt?: string;
    /**
     * The normalised half of the event, as a JSON object.  Edge is the hardware boundary (§C3), so the vendor\'s dialect stops there: this carries `plate`, `confidence` and so on, and never a `ZapPacket`. A string rather than a free-form object because it is stored verbatim and this contract takes no position on its keys. 
     */
    attributes?: string;
}

