/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GridName } from './grid-name';


export interface GridExport { 
    exportExternalId?: string;
    grid?: GridName;
    status?: GridExport.StatusEnum;
    contentType?: string;
    fileName?: string;
    rowCount?: number;
    createdAt?: string;
    completedAt?: string;
    body?: string;
}
export namespace GridExport {
    export const StatusEnum = {
        Completed: 'COMPLETED',
        Failed: 'FAILED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


