/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GridName } from './grid-name';


export interface GridExportRequest { 
    grid: GridName;
    laneExternalId?: string;
    assignee?: string;
    teamExternalId?: string;
    status?: GridExportRequest.StatusEnum;
    completedFrom?: string;
    completedUntil?: string;
    includeOutOfService?: boolean;
    limit?: number;
}
export namespace GridExportRequest {
    export const StatusEnum = {
        Completed: 'COMPLETED',
        Failed: 'FAILED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


