/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GridName = {
    LaneMonitors: 'LANE_MONITORS',
    Queue: 'QUEUE',
    Alerts: 'ALERTS',
    CompletedWork: 'COMPLETED_WORK'
} as const;
export type GridName = typeof GridName[keyof typeof GridName];

