/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LaneMonitor { 
    siteExternalId?: string;
    siteCode?: string;
    sitePrimary?: boolean;
    areaExternalId?: string;
    areaCode?: string;
    laneExternalId?: string;
    laneCode?: string;
    laneName?: string;
    lanePriority?: number;
    outOfService?: boolean;
    trafficStatus?: LaneMonitor.TrafficStatusEnum;
    trafficColor?: LaneMonitor.TrafficColorEnum;
    visitExternalId?: string;
    plate?: string;
    queuedWorkItemExternalId?: string;
    queuedWorkItemQueuedAt?: string;
    queuedWorkItemAssignee?: string;
    queuedWorkItemSlaBreachedAt?: string;
    gateArm?: string;
    redLamp?: string;
    orangeLamp?: string;
    greenLamp?: string;
    /**
     * JSON object of loop inputs last observed for the lane.
     */
    loopInputs?: string;
    lastDeviceEventUuid?: string;
    lastDeviceEventType?: string;
    lastDeviceObservedAt?: string;
    updatedAt?: string;
}
export namespace LaneMonitor {
    export const TrafficStatusEnum = {
        Clear: 'CLEAR',
        Active: 'ACTIVE',
        Completed: 'COMPLETED',
        Manual: 'MANUAL',
        Failed: 'FAILED'
    } as const;
    export type TrafficStatusEnum = typeof TrafficStatusEnum[keyof typeof TrafficStatusEnum];
    export const TrafficColorEnum = {
        Neutral: 'NEUTRAL',
        Blue: 'BLUE',
        Green: 'GREEN',
        Amber: 'AMBER',
        Red: 'RED'
    } as const;
    export type TrafficColorEnum = typeof TrafficColorEnum[keyof typeof TrafficColorEnum];
}


