/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LaneAlertReason } from './lane-alert-reason';


export interface LaneAlert { 
    laneExternalId?: string;
    laneCode?: string;
    laneName?: string;
    lanePriority?: number;
    trafficStatus?: LaneAlert.TrafficStatusEnum;
    trafficColor?: LaneAlert.TrafficColorEnum;
    visitExternalId?: string;
    plate?: string;
    queuedWorkItemExternalId?: string;
    queuedWorkItemQueuedAt?: string;
    queuedWorkItemSlaBreachedAt?: string;
    outOfService?: boolean;
    alertReasons?: Array<LaneAlertReason>;
}
export namespace LaneAlert {
    export const TrafficStatusEnum = {
        Clear: 'CLEAR',
        Active: 'ACTIVE',
        Completed: 'COMPLETED',
        Manual: 'MANUAL',
        Failed: 'FAILED'
    } as const;
    export type TrafficStatusEnum = typeof TrafficStatusEnum[keyof typeof TrafficStatusEnum];
    export const TrafficColorEnum = {
        Neutral: 'NEUTRAL',
        Blue: 'BLUE',
        Green: 'GREEN',
        Amber: 'AMBER',
        Red: 'RED'
    } as const;
    export type TrafficColorEnum = typeof TrafficColorEnum[keyof typeof TrafficColorEnum];
}


