/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const LaneAlertReason = {
    Manual: 'MANUAL',
    Failed: 'FAILED',
    SlaBreach: 'SLA_BREACH',
    OutOfService: 'OUT_OF_SERVICE'
} as const;
export type LaneAlertReason = typeof LaneAlertReason[keyof typeof LaneAlertReason];

