/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NamespaceNode { 
    uuid?: string;
    name?: string;
    type?: string;
    /**
     * The selector text an author would write to name this step\'s data.
     */
    selector?: string;
    /**
     * This step\'s data already exists at the editing point — a ranking hint for the builder, never a restriction. 
     */
    runsBefore?: boolean;
}

