/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Notification { 
    externalId?: string;
    recipientUserExternalId?: string;
    type?: string;
    title?: string;
    message?: string;
    payloadJson?: string;
    /**
     * Null means unread; no boolean read flag is stored.
     */
    readAt?: string;
    createdAt?: string;
}

