/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotificationWebSocketTicket { 
    /**
     * The bearer ticket to present when opening the WebSocket.
     */
    ticket?: string;
    expiresAt?: string;
}

