/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Pagination metadata, carried by the envelope rather than by headers or by each service\'s own invention. 
 */
export interface PageMeta { 
    /**
     * Zero-based page index.
     */
    page: number;
    /**
     * The page size actually applied, which may be smaller than the one asked for.
     */
    size: number;
    /**
     * Total matching items WITHIN THE CALLER\'S SCOPE. A count that escaped its scope would leak the size of what the caller cannot see. 
     */
    totalItems: number;
    totalPages: number;
}

