/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PresenceStatus = {
    Idle: 'IDLE',
    Working: 'WORKING',
    Dnd: 'DND',
    Break: 'BREAK',
    Offline: 'OFFLINE',
    Active: 'ACTIVE'
} as const;
export type PresenceStatus = typeof PresenceStatus[keyof typeof PresenceStatus];

