/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PresenceStatus } from './presence-status';


export interface PresenceActivity { 
    userExternalId?: string;
    status?: PresenceStatus;
    startedAt?: string;
    /**
     * Absent on the open row — the current status.
     */
    endedAt?: string;
}
export namespace PresenceActivity {
}


