/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NamespaceDatasetKey } from './namespace-dataset-key';
import { NamespaceWorkflow } from './namespace-workflow';
import { NamespaceNode } from './namespace-node';


export interface SelectorNamespace { 
    nodes?: Array<NamespaceNode>;
    datasetKeys?: Array<NamespaceDatasetKey>;
    workflows?: Array<NamespaceWorkflow>;
    /**
     * The evaluator\'s helper functions, as an author writes them.
     */
    helpers?: Array<string>;
}

