/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The payload of a service\'s own contracted health route.  Distinct from `/actuator/health`, which is the orchestrator\'s probe (§C1–C6) and is not part of any service\'s authored contract. 
 */
export interface ServiceHealth { 
    /**
     * The service answering, so a misrouted request is obvious.
     */
    service: string;
    status: ServiceHealth.StatusEnum;
}
export namespace ServiceHealth {
    export const StatusEnum = {
        Up: 'UP',
        Down: 'DOWN'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


