/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PresenceStatus } from './presence-status';


export interface SetPresenceRequest { 
    status: PresenceStatus;
}
export namespace SetPresenceRequest {
}


