/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ValidationFinding { 
    /**
     * The compiler invariant that would refuse this — the SAME name the compile failure carries, so a builder message and a deploy failure are traceably one thing. 
     */
    invariant?: string;
    /**
     * The node, link, branch or response uuid the author should look at. Absent when the finding is about the workflow as a whole.
     */
    subjectId?: string;
    /**
     * The authored name of that subject, because a uuid means nothing on a canvas.
     */
    subjectName?: string;
    /**
     * Plain language, addressed to an author rather than to a compiler engineer.
     */
    message?: string;
}

