/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationFinding } from './validation-finding';


export interface ValidationReport { 
    /**
     * Would this deploy — answered by really compiling, so the verdict and the deploy cannot disagree.
     */
    compiles?: boolean;
    findings?: Array<ValidationFinding>;
}

