/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Visit { 
    externalId?: string;
    laneExternalId?: string;
    /**
     * * `ACTIVE` — running, or parked at a step waiting for a person. * `COMPLETED` — the truck was released. * `MANUAL` — the process ended at a step a person resolved. * `FAILED` — the lane was reset under it. 
     */
    status?: Visit.StatusEnum;
    /**
     * The camera\'s most confident hypothesis, not its first. Absent when the event carried none.
     */
    plate?: string;
    startedAt?: string;
    completedAt?: string;
    /**
     * The step the engine is parked at, read live at request time. Absent when the visit is no longer running — a finished visit has no current step, and reporting its last one as current would be a lie a support engineer would act on. 
     */
    currentActivity?: string;
}
export namespace Visit {
    export const StatusEnum = {
        Active: 'ACTIVE',
        Completed: 'COMPLETED',
        Manual: 'MANUAL',
        Failed: 'FAILED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


