/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkItem { 
    externalId?: string;
    /**
     * The visit this item belongs to.
     */
    visitExternalId?: string;
    laneExternalId?: string;
    processDefinitionKey?: string;
    /**
     * The step in the process design — the screen identity\'s node reference points at this.
     */
    nodeReference?: string;
    /**
     * The screen identity this item renders with. Absent until the routing work package resolves it.
     */
    screenExternalId?: string;
    status?: WorkItem.StatusEnum;
    /**
     * The holding or pre-assigned operator\'s external id; absent = unassigned.
     */
    assignee?: string;
    queuedAt?: string;
    startedAt?: string;
    completedAt?: string;
    /**
     * Server-computed. The request can never supply it.
     */
    completionDurationSec?: number;
    /**
     * When the SLA timer on the wait state fired. Absent = not breached.
     */
    slaBreachedAt?: string;
    /**
     * The captured context of the step, as JSON.
     */
    eventData?: string;
    /**
     * What the operator submitted at completion.
     */
    correctedEventData?: string;
}
export namespace WorkItem {
    export const StatusEnum = {
        Queued: 'QUEUED',
        InProgress: 'IN_PROGRESS',
        Completed: 'COMPLETED',
        Failed: 'FAILED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


