/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkItemGridRequest { 
    laneExternalId?: string;
    assignee?: string;
    teamExternalId?: string;
    limit?: number;
}

