/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkItemAuditEntry { 
    action?: WorkItemAuditEntry.ActionEnum;
    actor?: string;
    previousAssignee?: string;
    occurredAt?: string;
    processingDurationSec?: number;
    elapsedSec?: number;
}
export namespace WorkItemAuditEntry {
    export const ActionEnum = {
        Take: 'TAKE',
        TakeOver: 'TAKE_OVER',
        Park: 'PARK',
        Assign: 'ASSIGN',
        Complete: 'COMPLETE',
        Fail: 'FAIL',
        SlaBreach: 'SLA_BREACH'
    } as const;
    export type ActionEnum = typeof ActionEnum[keyof typeof ActionEnum];
}


