-- Adds one column to the event buffer: the vendor's message, decoded into a plain
-- set of name/value pairs.
--
-- WHY A SECOND COLUMN RATHER THAN A REPLACEMENT FOR THE ONE THAT IS THERE
-- The existing `payload` column holds the bytes exactly as the camera sent them —
-- for the plate-reading cameras, a framed XML message between its start and end
-- delimiters. That stays. A durable buffer that stored a paraphrase of its input
-- would be worth less than one that did not: when a plate read is disputed, the
-- question is what the camera said, not what this service understood.
--
-- But this service is the hardware boundary, and a boundary that passed the
-- vendor's dialect through would put vendor-specific XML elements inside the
-- service that runs the gate — which is the opposite of a boundary. So the
-- vendor's format is decoded exactly once, here, and what crosses onward is this
-- small map of attributes. The gate never learns what the camera's message format
-- is called.
--
-- WHY IT IS DECODED ON ARRIVAL RATHER THAN ON DELIVERY
-- Because delivery retries, sometimes days later. If decoding happened at
-- delivery, a change to the parser between an event being buffered and eventually
-- being sent would change what an already-recorded row means. Decoding on arrival
-- settles the row at the moment it is written.
--
-- WHY IT IS NULLABLE, AND STAYS NULLABLE
-- Rows buffered before this migration ran have no decoded half, and they are not
-- rewritten — a schema change has to be readable by both the old and the new
-- version of the service for the length of a rolling upgrade, which means adding
-- rather than rewriting. Making the column NOT NULL with an empty default would
-- claim those rows had attributes and that the attributes were empty. That is a
-- different statement, and a false one.

ALTER TABLE event_buffer ADD attributes NVARCHAR(MAX) NULL;
