-- Flowable 8.0.0 — event registry, SQL Server.
--
-- EXTRACTED, NOT WRITTEN. Do not edit this file by hand.
--   source: flowable-event-registry-8.0.0.jar!/org/flowable/eventregistry/db/create/flowable.mssql.create.eventregistry.sql
--   regenerate: ./gradlew :services:orca-runtime:extractFlowableSchema
--
-- The engine does not migrate itself (flowable.database-schema-update: false),
-- because §B7 requires a schema change to be compatible with both versions for
-- the duration of a rolling upgrade, and self-migration on whichever instance
-- starts first cannot offer that.
--
-- UPGRADING FLOWABLE: do NOT re-extract this file. It has shipped, and an
-- expand-only discipline (§B7) means a migration is never edited after it does.
-- Extract that version's UPGRADE STEP scripts — flowable.mssql.upgradestep.*.sql,
-- in the same jars — as NEW migrations, in the order Flowable applies them.
--
CREATE TABLE FLW_EVENT_DEPLOYMENT (ID_ varchar(255) NOT NULL, NAME_ nvarchar(255), CATEGORY_ varchar(255), DEPLOY_TIME_ datetime, TENANT_ID_ varchar(255), PARENT_DEPLOYMENT_ID_ varchar(255), CONSTRAINT PK_FLW_EVENT_DEPLOYMENT PRIMARY KEY (ID_));

CREATE TABLE FLW_EVENT_RESOURCE (ID_ varchar(255) NOT NULL, NAME_ nvarchar(255), DEPLOYMENT_ID_ varchar(255), RESOURCE_BYTES_ varbinary(MAX), CONSTRAINT PK_FLW_EVENT_RESOURCE PRIMARY KEY (ID_));

CREATE TABLE FLW_EVENT_DEFINITION (ID_ varchar(255) NOT NULL, NAME_ nvarchar(255), VERSION_ int, KEY_ varchar(255), CATEGORY_ nvarchar(255), DEPLOYMENT_ID_ varchar(255), TENANT_ID_ varchar(255), RESOURCE_NAME_ nvarchar(255), DESCRIPTION_ nvarchar(255), CONSTRAINT PK_FLW_EVENT_DEFINITION PRIMARY KEY (ID_));

ALTER TABLE FLW_EVENT_RESOURCE
    ADD CONSTRAINT FLW_FK_EVENT_RSRC_DPL FOREIGN KEY (DEPLOYMENT_ID_) REFERENCES FLW_EVENT_DEPLOYMENT (ID_);

CREATE NONCLUSTERED INDEX FLW_IDX_EVENT_RSRC_DPL ON FLW_EVENT_RESOURCE(DEPLOYMENT_ID_);

CREATE UNIQUE NONCLUSTERED INDEX ACT_IDX_EVENT_DEF_UNIQ ON FLW_EVENT_DEFINITION(KEY_, VERSION_, TENANT_ID_);

CREATE TABLE FLW_CHANNEL_DEFINITION (ID_ varchar(255) NOT NULL, NAME_ nvarchar(255), VERSION_ int, KEY_ varchar(255), CATEGORY_ nvarchar(255), TYPE_ varchar(255), IMPLEMENTATION_ varchar(255), DEPLOYMENT_ID_ varchar(255), CREATE_TIME_ datetime, TENANT_ID_ varchar(255), RESOURCE_NAME_ nvarchar(255), DESCRIPTION_ nvarchar(255), CONSTRAINT PK_FLW_CHANNEL_DEFINITION PRIMARY KEY (ID_));

CREATE UNIQUE NONCLUSTERED INDEX ACT_IDX_CHANNEL_DEF_UNIQ ON FLW_CHANNEL_DEFINITION(KEY_, VERSION_, TENANT_ID_);

insert into ACT_GE_PROPERTY
values ('eventregistry.schema.version', '8.0.0.0', 1);
