/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { ApiResponse } from '../model/api-response';
// @ts-ignore
import { LaneResetEnvelope } from '../model/lane-reset-envelope';
// @ts-ignore
import { VisitEnvelope } from '../model/visit-envelope';
// @ts-ignore
import { VisitListEnvelope } from '../model/visit-list-envelope';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { RuntimeConfiguration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class VisitsService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: RuntimeConfiguration) {
        super(basePath, configuration);
    }

    /**
     * Abort this visit — terminate its process, fail its work items, free its lane
     * One transaction, and the same one lane reset performs: the process instance is terminated, the visit\&#39;s open work items are failed, and the lane is released for the next truck.  Addressed by visit rather than by lane, and the visit\&#39;s identity is re-checked under the lane lock — so a visit that finished while the request was in flight is refused rather than having the next truck aborted in its place.  Aborting a visit that is no longer running answers &#x60;409&#x60;. Unlike resetting an already-clear lane, which is an ordinary outcome, naming a specific visit and being wrong about its state is a mistake worth reporting. 
     * @endpoint post /api/v1/visits/{visitExternalId}/abort
     * @param visitExternalId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public abortVisit(visitExternalId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LaneResetEnvelope>;
    public abortVisit(visitExternalId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LaneResetEnvelope>>;
    public abortVisit(visitExternalId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LaneResetEnvelope>>;
    public abortVisit(visitExternalId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (visitExternalId === null || visitExternalId === undefined) {
            throw new Error('Required parameter visitExternalId was null or undefined when calling abortVisit.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/visits/${this.configuration.encodeParam({name: "visitExternalId", value: visitExternalId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/abort`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<LaneResetEnvelope>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * The visit running on this lane right now, if any
     * The lane\&#39;s current visit, with the step the engine is parked at.  **An empty lane answers &#x60;200&#x60; with a null &#x60;data&#x60;, not &#x60;404&#x60;.** A lane with no truck at it is the normal state of a gate, and reporting it as \&quot;not found\&quot; would make an ordinary condition indistinguishable from a misconfigured lane identifier.  A lane this installation does not publish answers &#x60;422&#x60; — that IS a configuration fault and must not read as \&quot;no truck here\&quot;. 
     * @endpoint get /api/v1/lanes/{laneExternalId}/visit
     * @param laneExternalId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getLaneVisit(laneExternalId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<VisitEnvelope>;
    public getLaneVisit(laneExternalId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<VisitEnvelope>>;
    public getLaneVisit(laneExternalId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<VisitEnvelope>>;
    public getLaneVisit(laneExternalId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (laneExternalId === null || laneExternalId === undefined) {
            throw new Error('Required parameter laneExternalId was null or undefined when calling getLaneVisit.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/lanes/${this.configuration.encodeParam({name: "laneExternalId", value: laneExternalId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/visit`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<VisitEnvelope>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * One visit, with the step it is currently parked at
     * The stored row **plus the engine\&#39;s live position** for a running visit — which is the reason this route exists on the owning module rather than on a projection. &#x60;currentActivity&#x60; is read from the engine at request time and is absent once the visit is no longer running. 
     * @endpoint get /api/v1/visits/{visitExternalId}
     * @param visitExternalId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getVisit(visitExternalId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<VisitEnvelope>;
    public getVisit(visitExternalId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<VisitEnvelope>>;
    public getVisit(visitExternalId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<VisitEnvelope>>;
    public getVisit(visitExternalId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (visitExternalId === null || visitExternalId === undefined) {
            throw new Error('Required parameter visitExternalId was null or undefined when calling getVisit.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/visits/${this.configuration.encodeParam({name: "visitExternalId", value: visitExternalId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<VisitEnvelope>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Search visits by lane, status and time window
     * **A bounded read of a traffic-growing table.** &#x60;execution&#x60; grows with every truck, so this never serves the whole table: &#x60;limit&#x60; is capped and a window that is not given defaults to recent activity rather than to all of history. Ordered newest first — the operational question is almost always about the last few minutes.  Scope is the installation\&#39;s own site, taken from configuration and never from the request. 
     * @endpoint get /api/v1/visits
     * @param laneExternalId 
     * @param status 
     * @param plate Exact match. The plate as the camera\&#39;s most confident hypothesis recorded it.
     * @param since Visits started at or after this instant. Absent means the last 24 hours — **a default window rather than no window**, because an unpredicated read of a traffic-growing table is how a support query becomes a table scan. 
     * @param limit 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public listVisits(laneExternalId?: string, status?: 'ACTIVE' | 'COMPLETED' | 'MANUAL' | 'FAILED', plate?: string, since?: string, limit?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<VisitListEnvelope>;
    public listVisits(laneExternalId?: string, status?: 'ACTIVE' | 'COMPLETED' | 'MANUAL' | 'FAILED', plate?: string, since?: string, limit?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<VisitListEnvelope>>;
    public listVisits(laneExternalId?: string, status?: 'ACTIVE' | 'COMPLETED' | 'MANUAL' | 'FAILED', plate?: string, since?: string, limit?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<VisitListEnvelope>>;
    public listVisits(laneExternalId?: string, status?: 'ACTIVE' | 'COMPLETED' | 'MANUAL' | 'FAILED', plate?: string, since?: string, limit?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'laneExternalId',
            <any>laneExternalId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'status',
            <any>status,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'plate',
            <any>plate,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'since',
            <any>since,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'limit',
            <any>limit,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/visits`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<VisitListEnvelope>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
