/**
 * orca-runtime
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { ApiResponse } from '../model/api-response';
// @ts-ignore
import { AssignWorkItemRequest } from '../model/assign-work-item-request';
// @ts-ignore
import { CompleteWorkItemRequest } from '../model/complete-work-item-request';
// @ts-ignore
import { WorkItemAuditEnvelope } from '../model/work-item-audit-envelope';
// @ts-ignore
import { WorkItemEnvelope } from '../model/work-item-envelope';
// @ts-ignore
import { WorkItemListEnvelope } from '../model/work-item-list-envelope';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { RuntimeConfiguration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class WorkItemsService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: RuntimeConfiguration) {
        super(basePath, configuration);
    }

    /**
     * Pre-assign to a chosen operator; the item stays QUEUED
     * @endpoint post /api/v1/work-items/{workItemExternalId}/assign
     * @param workItemExternalId 
     * @param assignWorkItemRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public assignWorkItem(workItemExternalId: string, assignWorkItemRequest: AssignWorkItemRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<WorkItemEnvelope>;
    public assignWorkItem(workItemExternalId: string, assignWorkItemRequest: AssignWorkItemRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<WorkItemEnvelope>>;
    public assignWorkItem(workItemExternalId: string, assignWorkItemRequest: AssignWorkItemRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<WorkItemEnvelope>>;
    public assignWorkItem(workItemExternalId: string, assignWorkItemRequest: AssignWorkItemRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (workItemExternalId === null || workItemExternalId === undefined) {
            throw new Error('Required parameter workItemExternalId was null or undefined when calling assignWorkItem.');
        }
        if (assignWorkItemRequest === null || assignWorkItemRequest === undefined) {
            throw new Error('Required parameter assignWorkItemRequest was null or undefined when calling assignWorkItem.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/work-items/${this.configuration.encodeParam({name: "workItemExternalId", value: workItemExternalId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/assign`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<WorkItemEnvelope>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: assignWorkItemRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Complete the item AND advance the parked process — one transaction
     * The inversion this phase exists for: the item\&#39;s completion and the engine\&#39;s advance commit together or not at all. There is no state where the console believes an item is done and the engine does not.  &#x60;completionDurationSec&#x60; is computed by the server from the item\&#39;s own clock — the request cannot supply it.  A submit for a step the engine is not waiting on — already completed, reset, or never this item\&#39;s step — is refused with a typed 409, and nothing moves. 
     * @endpoint post /api/v1/work-items/{workItemExternalId}/complete
     * @param workItemExternalId 
     * @param completeWorkItemRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public completeWorkItem(workItemExternalId: string, completeWorkItemRequest?: CompleteWorkItemRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<WorkItemEnvelope>;
    public completeWorkItem(workItemExternalId: string, completeWorkItemRequest?: CompleteWorkItemRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<WorkItemEnvelope>>;
    public completeWorkItem(workItemExternalId: string, completeWorkItemRequest?: CompleteWorkItemRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<WorkItemEnvelope>>;
    public completeWorkItem(workItemExternalId: string, completeWorkItemRequest?: CompleteWorkItemRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (workItemExternalId === null || workItemExternalId === undefined) {
            throw new Error('Required parameter workItemExternalId was null or undefined when calling completeWorkItem.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/work-items/${this.configuration.encodeParam({name: "workItemExternalId", value: workItemExternalId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/complete`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<WorkItemEnvelope>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: completeWorkItemRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * One item, with its captured and corrected data
     * @endpoint get /api/v1/work-items/{workItemExternalId}
     * @param workItemExternalId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getWorkItem(workItemExternalId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<WorkItemEnvelope>;
    public getWorkItem(workItemExternalId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<WorkItemEnvelope>>;
    public getWorkItem(workItemExternalId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<WorkItemEnvelope>>;
    public getWorkItem(workItemExternalId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (workItemExternalId === null || workItemExternalId === undefined) {
            throw new Error('Required parameter workItemExternalId was null or undefined when calling getWorkItem.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/work-items/${this.configuration.encodeParam({name: "workItemExternalId", value: workItemExternalId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<WorkItemEnvelope>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * The action trail for an item
     * @endpoint get /api/v1/work-items/{workItemExternalId}/audit
     * @param workItemExternalId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getWorkItemAudit(workItemExternalId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<WorkItemAuditEnvelope>;
    public getWorkItemAudit(workItemExternalId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<WorkItemAuditEnvelope>>;
    public getWorkItemAudit(workItemExternalId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<WorkItemAuditEnvelope>>;
    public getWorkItemAudit(workItemExternalId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (workItemExternalId === null || workItemExternalId === undefined) {
            throw new Error('Required parameter workItemExternalId was null or undefined when calling getWorkItemAudit.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/work-items/${this.configuration.encodeParam({name: "workItemExternalId", value: workItemExternalId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/audit`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<WorkItemAuditEnvelope>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * The queue, filtered
     * Queue membership is &#x60;status&#x60; + &#x60;queuedAt&#x60; + assignee — there is no queue table. **No &#x60;status&#x60; means the open queue** (QUEUED and IN_PROGRESS) — the table grows with traffic, and an unpredicated read would serve history, not work. Open-queue reads are ordered by the routing rules\&#39; priority — set before unset, lower more urgent, oldest-queued as the tiebreak; terminal-status reads are oldest first. 
     * @endpoint get /api/v1/work-items
     * @param status 
     * @param laneExternalId 
     * @param assignee 
     * @param teamExternalId Narrow to a team\&#39;s routed work — plus the unrouted items, which every grid shows because anyone may claim them. Ordering uses this team\&#39;s rule priorities. **Open-queue reads only**: on a terminal-status read the parameter is refused (422), because silently ignoring it would present every team\&#39;s history as one team\&#39;s. 
     * @param limit 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public listWorkItems(status?: 'QUEUED' | 'IN_PROGRESS' | 'COMPLETED' | 'FAILED', laneExternalId?: string, assignee?: string, teamExternalId?: string, limit?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<WorkItemListEnvelope>;
    public listWorkItems(status?: 'QUEUED' | 'IN_PROGRESS' | 'COMPLETED' | 'FAILED', laneExternalId?: string, assignee?: string, teamExternalId?: string, limit?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<WorkItemListEnvelope>>;
    public listWorkItems(status?: 'QUEUED' | 'IN_PROGRESS' | 'COMPLETED' | 'FAILED', laneExternalId?: string, assignee?: string, teamExternalId?: string, limit?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<WorkItemListEnvelope>>;
    public listWorkItems(status?: 'QUEUED' | 'IN_PROGRESS' | 'COMPLETED' | 'FAILED', laneExternalId?: string, assignee?: string, teamExternalId?: string, limit?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'status',
            <any>status,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'laneExternalId',
            <any>laneExternalId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'assignee',
            <any>assignee,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'teamExternalId',
            <any>teamExternalId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'limit',
            <any>limit,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/work-items`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<WorkItemListEnvelope>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Return an in-progress item to the queue
     * Park is re-queue — &#x60;IN_PROGRESS&#x60; → &#x60;QUEUED&#x60;, assignee and clock cleared. There is no distinct PARKED status; the design choice is stated in the phase report rather than inherited silently. 
     * @endpoint post /api/v1/work-items/{workItemExternalId}/park
     * @param workItemExternalId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public parkWorkItem(workItemExternalId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<WorkItemEnvelope>;
    public parkWorkItem(workItemExternalId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<WorkItemEnvelope>>;
    public parkWorkItem(workItemExternalId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<WorkItemEnvelope>>;
    public parkWorkItem(workItemExternalId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (workItemExternalId === null || workItemExternalId === undefined) {
            throw new Error('Required parameter workItemExternalId was null or undefined when calling parkWorkItem.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/work-items/${this.configuration.encodeParam({name: "workItemExternalId", value: workItemExternalId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/park`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<WorkItemEnvelope>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Claim the oldest queued item on this lane\&#39;s running visit
     * Take-by-lane, for an operator working a lane monitor rather than the queue.  A convenience over &#x60;POST /work-items/{id}/take&#x60; and nothing more: the same eligibility check, the same conditional UPDATE as the only race guard, the same typed &#x60;409&#x60; for the loser, the same &#x60;TAKE&#x60; audit row.  **Oldest queued first, not the queue grid\&#39;s priority order.** The grid ranks work across lanes; this answers \&quot;the next thing at this lane\&quot;, where one visit\&#39;s items are a sequence. 
     * @endpoint post /api/v1/lanes/{laneExternalId}/take-next
     * @param laneExternalId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public takeNextOnLane(laneExternalId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<WorkItemEnvelope>;
    public takeNextOnLane(laneExternalId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<WorkItemEnvelope>>;
    public takeNextOnLane(laneExternalId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<WorkItemEnvelope>>;
    public takeNextOnLane(laneExternalId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (laneExternalId === null || laneExternalId === undefined) {
            throw new Error('Required parameter laneExternalId was null or undefined when calling takeNextOnLane.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/lanes/${this.configuration.encodeParam({name: "laneExternalId", value: laneExternalId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/take-next`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<WorkItemEnvelope>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Claim the item — a guarded conditional update
     * &#x60;QUEUED&#x60; → &#x60;IN_PROGRESS&#x60;, exactly one winner. The loser receives a typed 409 carrying the item\&#39;s current state and holder — the conditional UPDATE is the only guard; there is no pre-check that can race. A pre-assigned item is claimable by its assignee only. 
     * @endpoint post /api/v1/work-items/{workItemExternalId}/take
     * @param workItemExternalId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public takeWorkItem(workItemExternalId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<WorkItemEnvelope>;
    public takeWorkItem(workItemExternalId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<WorkItemEnvelope>>;
    public takeWorkItem(workItemExternalId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<WorkItemEnvelope>>;
    public takeWorkItem(workItemExternalId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (workItemExternalId === null || workItemExternalId === undefined) {
            throw new Error('Required parameter workItemExternalId was null or undefined when calling takeWorkItem.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/work-items/${this.configuration.encodeParam({name: "workItemExternalId", value: workItemExternalId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/take`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<WorkItemEnvelope>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Supervisor takeover — reassigns and resets the clock, stays IN_PROGRESS
     * @endpoint post /api/v1/work-items/{workItemExternalId}/takeover
     * @param workItemExternalId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public takeoverWorkItem(workItemExternalId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<WorkItemEnvelope>;
    public takeoverWorkItem(workItemExternalId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<WorkItemEnvelope>>;
    public takeoverWorkItem(workItemExternalId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<WorkItemEnvelope>>;
    public takeoverWorkItem(workItemExternalId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (workItemExternalId === null || workItemExternalId === undefined) {
            throw new Error('Required parameter workItemExternalId was null or undefined when calling takeoverWorkItem.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/work-items/${this.configuration.encodeParam({name: "workItemExternalId", value: workItemExternalId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/takeover`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<WorkItemEnvelope>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
